#Generated by SpriteSheet#export ( http://github.com/ameuret/spritesheet).
# DO NOT EDIT.
module SpriteSheet
module Citydetails
sprites = {"cityDetails_000"=>{:path=>"../sprites/city/cityDetails_000.png", :x=>125, :y=>64, :w=>22, :h=>37}, "cityDetails_007"=>{:path=>"../sprites/city/cityDetails_007.png", :x=>103, :y=>64, :w=>22, :h=>37}, "cityDetails_010"=>{:path=>"../sprites/city/cityDetails_010.png", :x=>71, :y=>0, :w=>32, :h=>45}}
end
end
